### ISSUE TITLE
Parameters depending on compartment size

### ISSUE THREAD

**Issue by joanna-lewis** [PublicHealthEngland/pygom#21]
Hello,

I've been enjoying playing around a bit with this library - thank you!

A suggestion for an additional feature: Could you add functionality that allows ODEs to include parameters that are functions of compartment sizes? For example, to allow users to define force of infection as a function of the ODE variables and then use lambda in the ODEs themselves? This is straightforward to write into the ODEs for simple models, but it would be nice to be able to put in a more complex force of infection without making the ODEs very cumbersome.

**Comment by HWilliams-PHE** [comment]
Hello, 

Can you send an example so we can check this out for you please?

**Comment by HWilliams-PHE** [comment]
This can be done using derived parameters.
