### ISSUE TITLE
Creating environment with yaml file

### ISSUE THREAD

**Issue by HWilliams-PHE** [publichealthengland/pygom#25]
Is it possible to run the setup.py file at the same time as setting up the conda environment? 

Can the following be added to the instal_requires list in the setup.py file.  
sphinx>=1.4.1
sphinx_rtd_theme>=0.2.0
ipython
numpydoc

**Comment by HWilliams-PHE** [comment]
Also required in the yml file are git and jupyter.

**Comment by twomagpi** [comment]
Are these needed to run PyGOM or are the needed only for the documentation?

**Comment by twomagpi** [comment]
The easiest way might be to create an empty conda environment and then use conda on the requirements file
`conda install --file requirements.txt`
from the root of the package. I'm not sure that having another (we alrealy have requirements.txt and setup.py) source of the truth for the package requirements is sensible.
