### ISSUE TITLE
Improved helpfulness of error message

### ISSUE THREAD

**Issue by HWilliams-PHE** [publichealthengland/pygom#35]
Is it possible to print out which input state does not exist?

~\AppData\Local\Continuum\anaconda3\envs\pygom\lib\site-packages\pygom-0.1.3-py3.6.egg\pygom\model\base_ode_model.py in _extractStateSymbol(self, input_str)
   1184                 else:
   1185                     raise InputError("Cannot find input state, input %s " +
-> 1186                                      "likely to be a vector" % sym_name)
   1187             else:
   1188                 raise InputError("Input state: %s does not exist" % input_str)

InputError: Cannot find input state, input %s likely to be a vector

**Comment by twomagpi** [comment]
Should be fixec in 0.1.7 with a tidied error line
