### ISSUE TITLE
Confidence interval calculations not working

### ISSUE THREAD

**Issue by HWilliams-PHE** [PublicHealthEngland/pygom#37]
Cannot generate confidence intervals, have tried code from arxiv paper which also doesn't work.

**Comment by edwintye** [comment]
Can you provide a bit more information on the environment?  Would need the python, numpy, scipy, version at a minimum to replicate.

**Comment by HWilliams-PHE** [comment]
Putting this down as user error because I've now got it working. If something goes wrong again, I'll be more descriptive with the code and error messages.
