### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by AdedoyinOkuyelu** [PublicHealthEngland/pygom#7]
When i tried running the test, it failed giving the following error message: 
ImportError: No module named libsbml

it seems this package needed to run the script was not included in the requirements and needs to be downloaded first before installing. Do you have any ideas on how to do this or has similar errors been encountered?

**Comment by etyephe** [comment]
Latest #8 should fix the problem you are encountering.  Come back if it doesn't.  Should be working for both python version 2.7 and 3.4 in theory.

**Comment by etyephe** [comment]
Closing the issue as the travis builds have all passed in the past couple of pull request and now covers a wider range of python versino.
